// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rbyshtsidbkoloqjezjx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJieXNodHNpZGJrb2xvcWplemp4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIzNTgwODQsImV4cCI6MjA3NzkzNDA4NH0.Zm658w2Vgo6BChANTdTS6CMcftCgO3Iwo0D0BXfjHDE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});